### ISSUE TITLE
Weird debug messages

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/scfair#5]
There are weird debug messages on the https://sc-fair.org/explore tool.

For e.g., when we select a certain filter, it gives the number of hits

**Comment by walid-sbr** [comment]
fixed in this commit: [4716727](https://github.com/DeplanckeLab/scfair/commit/4716727deae3ecf01ac1555f45a2ceade4a5ab53)

**Comment by VincentGardeux** [comment]
There is still this message at the bottom: "20 results are available, use up and down arrow keys to navigate."
Can you move it at the top of the page maybe? Make it more visible?

**Comment by walid-sbr** [comment]
> There is still this message at the bottom: "20 results are available, use up and down arrow keys to navigate." Can you move it at the top of the page maybe? Make it more visible?

C'est built-in dans Datatable, je sais pas comment disable ça @fab-dav
