### ISSUE TITLE
UI de la page Explore et scrolling de la datatable (droite gauche)

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/scfair#9]
Dans le tool [https://sc-fair.org/explore](https://sc-fair.org/explore)

Quand on load la page, on ne voit pas toute la table. Il faut scroller à droite.
Or, la barre de scrolling initiale que l'on voit, ne correspond pas. Et donc on n'arrive pas à scroller correctement.

Il faut vraiment revoir ça:
- Soit compresser au max pour mettre tout dans une seule page.
- Soit faire une seule scrolling bar qui soit facilement utilisable
- Soit changer l'orientation de la table?

Actuellement j'ai ça:

![image](https://github.com/DeplanckeLab/scfair/assets/15444333/95d53552-be97-4931-8713-caa2dc95479f)

Il y a 3 scrolling bars... Mais une seule est utile

**Comment by walid-sbr** [comment]
Fixed in this branch `window-scroll` waiting for merging
